server:
  port: 8080
  servlet:
    context-path: /api
spring:
  main:
    # 由于虚拟线程是守护线程，如果所有线程都是虚拟线程，JVM会直接推出，官方建议开启以下属性避免主线程退出JVM
    keep-alive: true
  threads:
    virtual:
      # 开启虚拟线程
      enabled: true
  profiles:
    active: dev
# swagger配置
springdoc:
  # 访问路径
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    # OpenApi描述文档路径，默认为 /v3/api-docs
    path: /api-docs
  # 打印控制台日志
  show-actuator: false
# Art平台配置
art:
  auth:
    # token过期时间 单位：分钟
    token-expire-time: 60
    white-list:
      - /auth/login
      - /auth/logout
      - /auth/changePasswordWithTempToken
      - /swagger-ui.html
      - /api-docs/**
      - /swagger-ui/**
    secret-key: c7ee264fd80c4e169f473df493bf67fd
# mybatis-flex指定mapper.xml文件位置
mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/*.xml
  global-config:
    # 主键生成策略
    key-config:
      before: true
      key-type: generator
      value: snowFlakeId
# Sa-Token配置
sa-token:
  jwt-secret-key: c7ee264fd80c4e169f473df493bf67fd
  is-read-cookie: false