spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/art-engine?currentSchema=public
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      # 连接最大生命周期
      max-lifetime: 1800000      # 30分钟
      # 空闲超时应小于 maxLifetime
      idle-timeout: 600000       # 10分钟
      minimum-idle: 5            # 最小空闲连接数
      maximum-pool-size: 100     # 最大连接数
      connection-timeout: 30000  # 获取连接超时时间
      connection-test-query: SELECT 1  # 验证查询
      # 连接存活检查
      keepalive-time: 30000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:root}
      database: ${REDIS_DATABASE:0}
      timeout: 10s
      lettuce:
        pool:
          enabled: true
          max-active: 100
          max-idle: 20
          min-idle: 5
          max-wait: 3000ms
          time-between-eviction-runs: 10s
        shutdown-timeout: 200ms
    elasticsearch:
      repositories:
        enabled: false

management:
  health:
    elasticsearch:
      enabled: false
# Art平台配置
art:
  auth:
    # token过期时间 单位：分钟
    token-expire-time: 60
    white-list:
      - /auth/login
      - /auth/logout
      - /auth/changePasswordWithTempToken
      - /swagger-ui.html
      - /api-docs/**
      - /swagger-ui/**
      - /ai/chat
    secret-key: c7ee264fd80c4e169f473df493bf67fd
  ai-model:
    model: ${AI_MODEL:deepseek-v4-flash}
    endpoint: ${AI_ENDPOINT:https://opencode.ai/zen/go}
    request-path: ${AI_REQUEST_PATH:/v1/chat/completions}
    api-key: ${AI_API_KEY:123456}
    provider: openAI
    support-image: false
    only-base64-image: false
    support-audio: false
    support-video: false
    support-thinking: true
    thinking-enabled: true