spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.206.93:3306/aether?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: xuaihao1234A!
    hikari:
      # 连接最大生命周期
      max-lifetime: 1800000      # 30分钟
      # 空闲超时应小于 maxLifetime
      idle-timeout: 600000       # 10分钟
      minimum-idle: 5            # 最小空闲连接数
      maximum-pool-size: 100     # 最大连接数
      connection-timeout: 30000  # 获取连接超时时间
      connection-test-query: SELECT 1  # 验证查询
      # 连接存活检查
      keepalive-time: 30000
  data:
    redis:
      host: 47.95.206.93
      port: 6379
      password: xuaihao1234
      database: 0
      timeout: 10s
      lettuce:
        pool:
          enabled: true
          max-active: 100
          max-idle: 20
          min-idle: 5
          max-wait: 3000ms
          time-between-eviction-runs: 10s
        shutdown-timeout: 200ms
# Art平台配置
art:
  auth:
    # token过期时间 单位：分钟
    token-expire-time: 60
    white-list:
      - /auth/login
      - /auth/logout
      - /auth/changePasswordWithTempToken
      - /swagger-ui.html
      - /api-docs/**
      - /swagger-ui/**
    secret-key: c7ee264fd80c4e169f473df493bf67fd
  ai-model:
    api-key: 1234567890
    end-point: https://api.openai.com
    request-path: /v1/chat/completions
    model-name: gpt-4
    provider: openai
    support-image: false
    only-base64-image: false
    support-audio: false
    support-video: false
    support-thinking: false
    enabled-thinking: false
