# 基础配置
VERSION = 2.1.0
GROUP = com.art

# Spring Boot版本
SPRING_BOOT_VERSION = 3.4.11
# Spring dependency management
# Spring依赖管理版本
SPRING_DEPENDENCY_MANAGEMENT_VERSION = 1.1.7
# Lombok插件版本
LOMBOK_PLUGIN_VERSION = 6.3.0

# gradle配置
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
# 开启并行项目执行
org.gradle.parallel=true
# 配置最大工作线程数
org.gradle.workers.max=4