dependencies {

    api "${lib.'jjwt-api'}"
    api "${lib.'jjwt-impl'}"
    api "${lib.'jjwt-jackson'}"
    api "${lib.'commons-lang3'}"
    api "${lib.'lombok'}"
    api "${lib.'transmittable-thread-local'}"
    api "${lib.'mysql-connect-java'}"
    api "${lib.'reflections'}"
    api "${lib.'sa-token'}"
    api "${lib.'sa-token-jwt'}"

    api 'org.springframework.boot:spring-boot-starter'
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-jdbc'
    api 'org.apache.commons:commons-pool2'
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    api "${lib.'mybatis-flex'}"
    api "${lib.'fastjson'}"
    api "${lib.'hutool'}"
    api "${lib.'hikari-cp'}"
}