dependencies {
    implementation project(":art-core")
    implementation project(":art-log")
    implementation project(":art-ai")

    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'software.amazon.awssdk:s3:2.48.4'
    implementation 'software.amazon.awssdk:apache5-client:2.48.4'
}
