plugins {
    id 'io.spring.dependency-management' version "${SPRING_DEPENDENCY_MANAGEMENT_VERSION}"
    id 'org.springframework.boot' version "${SPRING_BOOT_VERSION}"
}
dependencies {
    implementation project(":art-ai")
    implementation project(":art-core")
    implementation project(":art-system")
    implementation project(":art-log")
    implementation project(":art-websocket")

    testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'
}

// 编译项目版本信息
springBoot {
    buildInfo()
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = "${project.name}-${project.version}.jar"
}